In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

## Load canonical dataset

In [2]:
import pandas as pd

raw_path = "../data/raw_data/APL_Logistics.csv"

df = pd.read_csv(
    raw_path,
    encoding="cp1252"
)

print("Dataset loaded successfully.")
print("Shape:", df.shape)

Dataset loaded successfully.
Shape: (180519, 40)

## Inspect the dataset

In [3]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nColumn Names:")
print(df.columns.tolist())

print("\nFirst 5 Rows:")
display(df.head())

print("\nLast 5 Rows:")
display(df.tail())

Rows: 180519
Columns: 40

Column Names:
['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)', 'Benefit per order', 'Sales per customer', 'Delivery Status', 'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City', 'Customer Country', 'Customer Fname', 'Customer Id', 'Customer Lname', 'Customer Segment', 'Customer State', 'Customer Street', 'Customer Zipcode', 'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market', 'Order City', 'Order Country', 'Order Customer Id', 'Order Item Discount', 'Order Item Discount Rate', 'Order Item Product Price', 'Order Item Profit Ratio', 'Order Item Quantity', 'Sales', 'Order Item Total', 'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status', 'Product Name', 'Product Price', 'Shipping Mode']

First 5 Rows:

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Fname,Customer Id,Customer Lname,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,Order Item Discount,Order Item Discount Rate,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Name,Product Price,Shipping Mode
0,DEBIT,6,4,159.69,472.45,Late delivery,1,9,Cardio Equipment,Brownsville,EE. UU.,Richard,1,Hernandez,Consumer,TX,6303 Heather Plaza,78521.0,3,Footwear,25.953648,-97.507683,Pacific Asia,Mumbai,India,1,27.50,0.06,99.99,0.34,5,499.95,472.45,159.69,South Asia,Maharashtra,COMPLETE,Nike Men's Free 5.0+ Running Shoe,99.99,Standard Class
1,DEBIT,4,4,48.71,167.96,Shipping on time,0,29,Shop By Sport,Littleton,EE. UU.,Mary,2,Barrett,Consumer,CO,9526 Noble Embers Ridge,80126.0,5,Golf,38.375595,-104.726021,LATAM,San Pedro Sula,Honduras,2,31.99,0.16,39.99,0.29,5,199.95,167.96,48.71,Central America,Cortés,ON_HOLD,Under Armour Girls' Toddler Spine Surge Runni,39.99,Standard Class
2,DEBIT,4,4,87.36,181.99,Shipping on time,0,48,Water Sports,Littleton,EE. UU.,Mary,2,Barrett,Consumer,CO,9526 Noble Embers Ridge,80126.0,7,Fan Shop,38.375595,-104.726021,LATAM,San Pedro Sula,Honduras,2,18.00,0.09,199.99,0.48,1,199.99,181.99,87.36,Central America,Cortés,ON_HOLD,Pelican Sunstream 100 Kayak,199.99,Standard Class
3,DEBIT,6,4,-41.89,175.99,Late delivery,1,48,Water Sports,Littleton,EE. UU.,Mary,2,Barrett,Consumer,CO,9526 Noble Embers Ridge,80126.0,7,Fan Shop,38.375595,-104.726021,USCA,New York City,Estados Unidos,2,24.00,0.12,199.99,-0.24,1,199.99,175.99,-41.89,East of USA,Nueva York,COMPLETE,Pelican Sunstream 100 Kayak,199.99,Standard Class
4,DEBIT,6,4,10.00,40.00,Late delivery,1,24,Women's Apparel,Littleton,EE. UU.,Mary,2,Barrett,Consumer,CO,9526 Noble Embers Ridge,80126.0,5,Golf,38.375595,-104.726021,USCA,New York City,Estados Unidos,2,10.00,0.20,50.00,0.25,1,50.00,40.00,10.00,East of USA,Nueva York,COMPLETE,Nike Men's Dri-FIT Victory Golf Polo,50.00,Standard Class

Last 5 Rows:

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Fname,Customer Id,Customer Lname,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,Order Item Discount,Order Item Discount Rate,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Name,Product Price,Shipping Mode
180514,TRANSFER,6,4,-107.96,161.87,Late delivery,1,76,Women's Clothing,Caguas,Puerto Rico,Chava,20753,Velez,Consumer,PR,9861 Grand Elk Trace,725.0,4,Apparel,18.273024,-66.037056,Pacific Asia,Bekasi,Indonesia,20753,53.96,0.25,215.82,-0.67,1,215.82,161.87,-107.96,Southeast Asia,Java Occidental,PROCESSING,Summer dresses,215.82,Standard Class
180515,DEBIT,2,4,-126.56,172.66,Advance shipping,0,76,Women's Clothing,Plainfield,EE. UU.,Stacey,20754,Weber,Consumer,IL,5919 Hidden Anchor Port,60544.0,4,Apparel,41.608639,-88.202042,Pacific Asia,Bekasi,Indonesia,20754,43.16,0.20,215.82,-0.73,1,215.82,172.66,-126.56,Southeast Asia,Java Occidental,COMPLETE,Summer dresses,215.82,Standard Class
180516,DEBIT,3,4,91.25,314.64,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Cally,20755,Holloway,Consumer,PR,5365 Noble Nectar Island,725.0,2,Fitness,18.251453,-66.037056,Pacific Asia,Bekasi,Indonesia,20755,13.11,0.04,327.75,0.29,1,327.75,314.64,91.25,Southeast Asia,Java Occidental,COMPLETE,Smart watch,327.75,Standard Class
180517,PAYMENT,4,4,1.53,10.91,Shipping on time,0,74,Toys,Berwyn,EE. UU.,Cherokee,20756,Callahan,Corporate,IL,3312 Harvest Horse Chase,60402.0,7,Fan Shop,41.830791,-87.802979,Pacific Asia,Bekasi,Indonesia,20756,0.63,0.06,11.54,0.14,1,11.54,10.91,1.53,Southeast Asia,Java Occidental,PENDING_PAYMENT,Toys,11.54,Standard Class
180518,CASH,1,0,9.79,34.98,Late delivery,1,75,Video Games,Miami,EE. UU.,Katelyn,20757,Gonzales,Corporate,FL,9299 Quiet Pioneer Forest,33126.0,9,Discs Shop,25.860285,-80.197342,Pacific Asia,Gold Coast,Australia,20757,4.77,0.12,39.75,0.28,1,39.75,34.98,9.79,Oceania,Queensland,CLOSED,Fighting video games,39.75,Same Day

## Check the data types

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Fname                 180519 non-null  str
 12  Customer Id                    180519 non-null  int64
 13  Customer Lname                 180511 non-null  str
 14  Customer Segment               180519 non-null  str
 15  Customer State                 180519 non-null  str
 16  Customer Street                180519 non-null  str
 17  Customer Zipcode               180516 non-null  float64
 18  Department Id                  180519 non-null  int64
 19  Department Name                180519 non-null  str
 20  Latitude                       180519 non-null  float64
 21  Longitude                      180519 non-null  float64
 22  Market                         180519 non-null  str
 23  Order City                     180519 non-null  str
 24  Order Country                  180519 non-null  str
 25  Order Customer Id              180519 non-null  int64
 26  Order Item Discount            180519 non-null  float64
 27  Order Item Discount Rate       180519 non-null  float64
 28  Order Item Product Price       180519 non-null  float64
 29  Order Item Profit Ratio        180519 non-null  float64
 30  Order Item Quantity            180519 non-null  int64
 31  Sales                          180519 non-null  float64
 32  Order Item Total               180519 non-null  float64
 33  Order Profit Per Order         180519 non-null  float64
 34  Order Region                   180519 non-null  str
 35  Order State                    180519 non-null  str
 36  Order Status                   180519 non-null  str
 37  Product Name                   180519 non-null  str
 38  Product Price                  180519 non-null  float64
 39  Shipping Mode                  180519 non-null  str
dtypes: float64(13), int64(8), str(19)
memory usage: 90.2 MB

In [5]:
dtype_summary = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.astype(str).values
})

display(dtype_summary)

                           Column Data_Type
0                            Type       str
1        Days for shipping (real)     int64
2   Days for shipment (scheduled)     int64
3               Benefit per order   float64
4              Sales per customer   float64
5                 Delivery Status       str
6              Late_delivery_risk     int64
7                     Category Id     int64
8                   Category Name       str
9                   Customer City       str
10               Customer Country       str
11                 Customer Fname       str
12                    Customer Id     int64
13                 Customer Lname       str
14               Customer Segment       str
15                 Customer State       str
16                Customer Street       str
17               Customer Zipcode   float64
18                  Department Id     int64
19                Department Name       str
20                       Latitude   float64
21                      Longitude   float64
22                         Market       str
23                     Order City       str
24                  Order Country       str
25              Order Customer Id     int64
26            Order Item Discount   float64
27       Order Item Discount Rate   float64
28       Order Item Product Price   float64
29        Order Item Profit Ratio   float64
30            Order Item Quantity     int64
31                          Sales   float64
32               Order Item Total   float64
33         Order Profit Per Order   float64
34                   Order Region       str
35                    Order State       str
36                   Order Status       str
37                   Product Name       str
38                  Product Price   float64
39                  Shipping Mode       str

## Missing value analysis

In [6]:
missing = pd.DataFrame({
    "Column": df.columns,
    "Missing_Count": df.isnull().sum().values,
    "Missing_Percentage": (
        df.isnull().mean().values * 100
    )
})

missing = missing.sort_values(
    "Missing_Count",
    ascending=False
)

display(missing[missing["Missing_Count"] > 0])

              Column  Missing_Count  Missing_Percentage
13    Customer Lname              8            0.004432
17  Customer Zipcode              3            0.001662

## Duplicate check

In [7]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

## Checking unique values of important categorical fields

In [8]:
categorical_columns = [
    "Type",
    "Delivery Status",
    "Customer Segment",
    "Market",
    "Order Status",
    "Shipping Mode"
]

for col in categorical_columns:
    print("\n" + "=" * 60)
    print(col)
    print("=" * 60)
    print(df[col].value_counts(dropna=False))

============================================================
Type
============================================================
Type
DEBIT       69295
TRANSFER    49883
PAYMENT     41725
CASH        19616
Name: count, dtype: int64

============================================================
Delivery Status
============================================================
Delivery Status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

============================================================
Customer Segment
============================================================
Customer Segment
Consumer       93504
Corporate      54789
Home Office    32226
Name: count, dtype: int64

============================================================
Market
============================================================
Market
LATAM           51594
Europe          50252
Pacific Asia    41260
USCA            25799
Africa          11614
Name: count, dtype: int64

============================================================
Order Status
============================================================
Order Status
COMPLETE           59491
PENDING_PAYMENT    39832
PROCESSING         21902
PENDING            20227
CLOSED             19616
ON_HOLD             9804
SUSPECTED_FRAUD     4062
CANCELED            3692
PAYMENT_REVIEW      1893
Name: count, dtype: int64

============================================================
Shipping Mode
============================================================
Shipping Mode
Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: count, dtype: int64

## Validate the shipping duration fields

In [9]:
shipping_columns = [
    "Days for shipping (real)",
    "Days for shipment (scheduled)"
]

display(df[shipping_columns].describe())

       Days for shipping (real)  Days for shipment (scheduled)
count             180519.000000                  180519.000000
mean                   3.497654                       2.931847
std                    1.623722                       1.374449
min                    0.000000                       0.000000
25%                    2.000000                       2.000000
50%                    3.000000                       4.000000
75%                    5.000000                       4.000000
max                    6.000000                       4.000000

In [10]:
for col in shipping_columns:
    print("\n", col)
    print(sorted(df[col].dropna().unique()))

 Days for shipping (real)
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6)]

 Days for shipment (scheduled)
[np.int64(0), np.int64(1), np.int64(2), np.int64(4)]

## Validate (Late delivery risk)

In [11]:
print(df["Late_delivery_risk"].value_counts())

print("\nPercentage:")
print(
    df["Late_delivery_risk"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Late_delivery_risk
1    98977
0    81542
Name: count, dtype: int64

Percentage:
Late_delivery_risk
1    54.83
0    45.17
Name: proportion, dtype: float64

In [12]:
valid_risk_values = {0, 1}

actual_risk_values = set(
    df["Late_delivery_risk"].dropna().unique()
)

print("Risk values:", actual_risk_values)

if actual_risk_values.issubset(valid_risk_values):
    print("Late_delivery_risk validation: PASS")
else:
    print("Late_delivery_risk validation: CHECK REQUIRED")

Risk values: {np.int64(0), np.int64(1)}
Late_delivery_risk validation: PASS

## Validate delivery status

In [13]:
print(df["Delivery Status"].value_counts())

Delivery Status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

## Basic numeric validation

In [14]:
numeric_columns = df.select_dtypes(
    include=["int64", "float64"]
).columns

numeric_summary = df[numeric_columns].describe().T

display(numeric_summary)

,count,mean,std,min,25%,50%,75%,max
Days for shipping (real),180519.0,3.497654,1.623722,0.000000,2.000000,3.000000,5.000000,6.000000
Days for shipment (scheduled),180519.0,2.931847,1.374449,0.000000,2.000000,4.000000,4.000000,4.000000
Benefit per order,180519.0,21.974989,104.433526,-4274.980000,7.000000,31.520000,64.800000,911.800000
Sales per customer,180519.0,183.107607,120.043668,7.490000,104.380000,163.990000,247.400000,1939.990000
Late_delivery_risk,180519.0,0.548291,0.497664,0.000000,0.000000,1.000000,1.000000,1.000000
Category Id,180519.0,31.851451,15.640064,2.000000,18.000000,29.000000,45.000000,76.000000
Customer Id,180519.0,6691.379495,4162.918106,1.000000,3258.500000,6457.000000,9779.000000,20757.000000
Customer Zipcode,180516.0,35921.126914,37542.461122,603.000000,725.000000,19380.000000,78207.000000,99205.000000
Department Id,180519.0,5.443460,1.629246,2.000000,4.000000,5.000000,7.000000,12.000000
Latitude,180519.0,29.719955,9.813646,-33.937553,18.265432,33.144863,39.279617,48.781933
Longitude,180519.0,-84.915675,21.433241,-158.025986,-98.446312,-76.847908,-66.370583,115.263077
Order Customer Id,180519.0,6691.379495,4162.918106,1.000000,3258.500000,6457.000000,9779.000000,20757.000000
Order Item Discount,180519.0,20.664741,21.800901,0.000000,5.400000,14.000000,29.990000,500.000000
Order Item Discount Rate,180519.0,0.101668,0.070415,0.000000,0.040000,0.100000,0.160000,0.250000
Order Item Product Price,180519.0,141.232547,139.732489,9.990000,50.000000,59.990000,199.990000,1999.990000
Order Item Profit Ratio,180519.0,0.120647,0.466796,-2.750000,0.080000,0.270000,0.360000,0.500000
Order Item Quantity,180519.0,2.127638,1.453451,1.000000,1.000000,1.000000,3.000000,5.000000
Sales,180519.0,203.772092,132.273075,9.990000,119.980000,199.920000,299.950000,1999.990000
Order Item Total,180519.0,183.107607,120.043668,7.490000,104.380000,163.990000,247.400000,1939.990000
Order Profit Per Order,180519.0,21.974989,104.433526,-4274.980000,7.000000,31.520000,64.800000,911.800000
Product Price,180519.0,141.232547,139.732489,9.990000,50.000000,59.990000,199.990000,1999.990000

In [15]:
checks = {
    "Negative shipping days":
        (df["Days for shipping (real)"] < 0).sum(),

    "Negative scheduled days":
        (df["Days for shipment (scheduled)"] < 0).sum(),

    "Invalid late risk":
        (~df["Late_delivery_risk"].isin([0, 1])).sum(),

    "Negative quantity":
        (df["Order Item Quantity"] <= 0).sum(),

    "Negative discount":
        (df["Order Item Discount"] < 0).sum(),

    "Negative discount rate":
        (df["Order Item Discount Rate"] < 0).sum()
}

for check, count in checks.items():
    print(f"{check}: {count}")

Negative shipping days: 0
Negative scheduled days: 0
Invalid late risk: 0
Negative quantity: 0
Negative discount: 0
Negative discount rate: 0

## Handle missing values carefully

In [16]:
df["Customer Lname"] = df["Customer Lname"].fillna("Unknown")
df["Customer Zipcode"] = df["Customer Zipcode"].fillna("Unknown")

## Standardize text fields

In [17]:
# Strip leading/trailing whitespace from text columns
# Exclude Customer Zipcode because it contains numeric values

text_columns = df.select_dtypes(
    include=["object", "string"]
).columns

text_columns = text_columns.drop(
    "Customer Zipcode",
    errors="ignore"
)

for col in text_columns:
    df[col] = df[col].str.strip()

## Check the final Day 1 quality

In [18]:
print("Final Shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum()[df.isnull().sum() > 0])

print("\nDuplicate rows:")
print(df.duplicated().sum())

Final Shape: (180519, 40)

Missing values:
Series([], dtype: int64)

Duplicate rows:
0

## Saving the cleaned dataset

In [19]:
cleaned_path = "../data/cleaned_data/APL_Day1_Cleaned.csv"

df.to_csv(
    cleaned_path,
    index=False,
    encoding="cp1252"
)

print("Day 1 cleaned dataset saved successfully.")
print(cleaned_path)

Day 1 cleaned dataset saved successfully.
../data/cleaned_data/APL_Day1_Cleaned.csv